"""Native Gemma audio against locally initialized Transformers 5.16.1.

The fixtures are generated by tools/audio_reference.py. CPU fp32 observed
projector errors: Gemma 3n 7.2e-7, Gemma 4 2.1e-6. Input gradient errors
are 5.3e-10 and 8.4e-9; post-SGD errors 1.1e-6 and 1.4e-6. The 1e-4
forward bound allows accumulated GEMM/reduction rounding and rejects the
wrong Gemma 4 left-window boundary (0.026 before correction).
"""

import dataclasses
import json
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import optax
import pytest
from safetensors.numpy import load_file

from dew.data.audio import AudioProcessor
from dew.nn import vision as V
from dew.nn.audio import Gemma3nAudio, audio_config, audio_weight_path, audio_weights
from dew.nn.vision import (Gemma3nProjectorModule, Gemma4ProjectorModule,
                           translate_gemma3n_projector_weights, translate_gemma4_projector_weights)


FIXTURES = Path(__file__).parent / "fixtures" / "audio"


on_gpu = pytest.mark.skipif(jax.default_backend() != 'gpu',
                            reason="needs a cuda device")


def _audio(kind):
    path = FIXTURES / kind
    record = json.loads((path / "config.json").read_text())
    config = audio_config(record)
    variables = audio_weights(load_file(str(path / "encoder.safetensors")), config)
    model = config.build().clone(precision=jax.lax.Precision.HIGHEST)
    tensors = load_file(str(path / "projector.safetensors"))
    if kind == "gemma3n":
        projector = Gemma3nProjectorModule(config.hidden_size, 32, vocab_size=record["vocab_size"],
                                           vocab_offset=record["vocab_offset"], norm_eps=config.rms_norm_eps,
                                           precision=jax.lax.Precision.HIGHEST)
        method = projector.soft_embeddings
        projector_variables = {"params": translate_gemma3n_projector_weights(tensors)}
    else:
        projector = Gemma4ProjectorModule(text_width=32, norm_eps=config.rms_norm_eps,
                                          precision=jax.lax.Precision.HIGHEST)
        method = projector.__call__
        projector_variables = {"params": translate_gemma4_projector_weights(tensors)}
    return path, config, variables, model, projector, method, projector_variables


@pytest.fixture(params=("gemma3n", "gemma4"), scope="module")
def audio(request):
    return _audio(request.param)

def test_waveform_preprocessing_encoder_and_projection_match_reference(audio):
    path, config, variables, model, projector, method, projector_variables = audio
    data = np.load(path / "reference.npz")
    preprocessor = json.loads((path / "preprocessor_config.json").read_text())
    kind = "gemma3n_audio" if isinstance(config, Gemma3nAudio) else "gemma4_audio"
    process = AudioProcessor(kind, preprocessor)
    waveforms = [np.load(path / f"waveform_{index}.npy") for index in range(2)]
    features = process(waveforms, sampling_rate=16000)
    np.testing.assert_array_equal(features["input_features_mask"], data["input_features_mask"])
    np.testing.assert_allclose(features["input_features"], data["input_features"], rtol=0, atol=1e-6)
    encoded = jax.jit(model.apply)(variables, **features)
    np.testing.assert_array_equal(encoded.mask, data["valid"])
    np.testing.assert_allclose(encoded.features, data["encoded"], rtol=0, atol=1e-4)
    projected = projector.apply(projector_variables, encoded.features, method=method)
    np.testing.assert_allclose(projected, data["projected"], rtol=0, atol=1e-4)
    assert encoded.mask.dtype == jnp.bool_
    assert encoded.features.dtype == jnp.float32


@on_gpu
def test_encoder_compiles_on_gpu_with_the_mask_built_in_the_same_jit(audio):
    """Frame subsampling must leave no strided slice on a dot's operand chain.

    XLA's Triton GEMM fusion propagates a dot's tiling into its operands and
    mishandles a strided slice, aborting the process with
    `triton_tiling_propagation.cc: Check failed: src_fragment_it !=
    src_fragments_order.end()` as soon as anything fusible produces the
    sliced tensor. Deriving the mask from clip lengths inside the same jit
    puts such a producer above every frame subsample, which the encoder's
    former `mask[:, ::stride]` did not survive. Run with JAX_PLATFORMS=cuda.
    """
    path, _, variables, model, _, _, _ = audio
    data = np.load(path / "reference.npz")

    @jax.jit
    def encode(variables, features, lengths):
        return model.apply(variables, features,
                           jnp.arange(features.shape[1])[None, :] < lengths[:, None])

    encoded = encode(variables, jnp.asarray(data["input_features"]),
                     jnp.asarray(data["input_features_mask"].sum(1, dtype=np.int32)))
    np.testing.assert_array_equal(encoded.mask, data["valid"])
    np.testing.assert_allclose(encoded.features, data["encoded"], rtol=0, atol=1e-4)


def test_audio_input_gradients_and_sgd_step_match_reference(audio):
    path, _, variables, model, projector, method, projector_variables = audio
    data = np.load(path / "reference.npz")
    state = {"encoder": variables["params"], "projector": projector_variables["params"]}

    def forward(params, inputs):
        encoded = model.apply({**variables, "params": params["encoder"]}, inputs,
                               data["input_features_mask"])
        return projector.apply({"params": params["projector"]}, encoded.features, method=method)

    def loss(params, inputs):
        return jnp.mean(forward(params, inputs) * data["coefficient"])

    value, (grads, input_grad) = jax.jit(jax.value_and_grad(loss, argnums=(0, 1)))(state, data["input_features"])
    np.testing.assert_allclose(value, data["loss"], rtol=0, atol=1e-6)
    np.testing.assert_allclose(input_grad, data["input_gradient"], rtol=1e-4, atol=1e-7)
    optimizer = optax.sgd(json.loads((path / "meta.json").read_text())["learning_rate"])
    update, _ = optimizer.update(grads, optimizer.init(state), state)
    output = jax.jit(forward)(optax.apply_updates(state, update), data["input_features"])
    np.testing.assert_allclose(output, np.load(path / "stepped.npy"), rtol=0, atol=1e-4)


def test_gemma4_checkpoint_clipping_bounds_change_the_computation():
    path, _, variables, model, _, _, _ = _audio("gemma4")
    data = np.load(path / "reference.npz")
    # Removing checkpointed clipping changes the published computation.
    bounds = jax.tree_util.tree_map_with_path(
        lambda path, value: jnp.full_like(value, -jnp.inf if path[-1].key.endswith("min") else jnp.inf),
        variables["constants"])
    changed = jax.jit(model.apply)({**variables, "constants": bounds}, data["input_features"],
                                  data["input_features_mask"])
    assert np.max(np.abs(np.asarray(changed.features) - data["encoded"])) > 1e-3



def test_audio_mask_and_feature_shape_are_part_of_the_contract(audio):
    _, config, variables, model, _, _, _ = audio
    features = config.input_feat_size if isinstance(config, Gemma3nAudio) else config.subsampling_conv_channels[0]
    with pytest.raises(ValueError, match="input_features_mask"):
        model.apply(variables, jnp.ones((1, 16, features)), jnp.ones((1, 16), jnp.int32))
    with pytest.raises(ValueError, match="input_features"):
        model.apply(variables, jnp.ones((1, 16, features + 1)), jnp.ones((1, 16), jnp.bool_))
    with pytest.raises(ValueError, match="input_features_mask"):
        model.apply(variables, jnp.ones((1, 16, features)), jnp.ones((1, 15), jnp.bool_))


def test_audio_weight_loading_refuses_unknown_or_missing_computation(audio):
    path, config, _, _, _, _, _ = audio
    tensors = load_file(str(path / "encoder.safetensors"))
    first = next(iter(tensors))
    incomplete = dict(tensors)
    del incomplete[first]
    with pytest.raises(ValueError, match="missing"):
        audio_weights(incomplete, config)
    with pytest.raises(ValueError, match="does not match"):
        audio_weights({**tensors, "imaginary_projection.weight": np.ones((4, 4), np.float32)}, config)
    record = json.loads((path / "config.json").read_text())
    with pytest.raises(ValueError, match="no counterpart"):
        audio_config({**record, "extra_computational_field": True})
    rebuilt = audio_config({**dataclasses.asdict(config), "model_type": record["model_type"]})
    assert rebuilt == config
    assert V.tower_from_record({"kind": record["model_type"], **dataclasses.asdict(config)}) == config


def test_audio_weight_paths_round_trip_every_checkpoint_tensor(audio):
    """The canonical mapper resolves each source tensor to its loaded leaf."""
    path, config, variables, _, _, _, _ = audio
    tensors = load_file(str(path / "encoder.safetensors"))
    for name, tensor in tensors.items():
        leaf = variables
        for part in audio_weight_path(name, config):
            leaf = leaf[part]
        restored = np.asarray(leaf)
        if tensor.ndim > 1:
            restored = restored.transpose(restored.ndim - 1, restored.ndim - 2, *range(restored.ndim - 2))
        np.testing.assert_array_equal(restored, tensor)


def test_processor_rejects_wrong_sampling_rate_without_resampling():
    processor = AudioProcessor("gemma4_audio", {"feature_size": 16})
    with pytest.raises(ValueError, match="sampling_rate"):
        processor(np.ones(1000, np.float32), sampling_rate=8000)
    with pytest.raises(ValueError, match="nonempty mono"):
        processor([np.ones((100, 2), np.float32)], sampling_rate=16000)


def test_released_geometries_emit_the_processor_token_counts():
    """30 s of 10 ms frames become 188 Gemma 3n and 750 Gemma 4 soft tokens.

    Those are the counts the checkpoint processors expand (Gemma3nProcessor
    audio_seq_length=188, Gemma4Processor audio_seq_length=750). Checked
    abstractly, without allocating the 681M and 305M encoder parameters.
    """
    released = json.loads((FIXTURES.parent / "hf" / "gemma-3n-e2b" / "config.json").read_text())["audio_config"]
    for record, tokens in ((released, 188), ({"model_type": "gemma4_audio"}, 750)):
        encoder = audio_config(record).build()
        output, _ = jax.eval_shape(encoder.init_with_output, jax.random.key(0),
                                   jax.ShapeDtypeStruct((1, 3000, 128), jnp.float32),
                                   jax.ShapeDtypeStruct((1, 3000), jnp.bool_))
        assert output.features.shape[:2] == (1, tokens)
        assert output.mask.shape == (1, tokens)
