"""Actual saved SD/SDXL pipelines, not mocked components or solver aliases.

The archive was generated by tools/diffusers_pipeline_reference.py against
Diffusers 0.34.0 / Transformers 4.49.0. Runtime checks use the installed current
Transformers stack. fp32 CPU observed max error: 0 for all four trajectories;
3e-5 absolute/relative allows backend floating-point contraction differences.
"""
import os
from pathlib import Path
import subprocess
import sys
import tarfile

import pytest

pytest.importorskip("diffusers")
ROOT = Path(__file__).resolve().parents[1]


@pytest.fixture(scope="module")
def saved_pipelines(tmp_path_factory):
    destination = tmp_path_factory.mktemp("saved-diffusers")
    with tarfile.open(ROOT / "tests/fixtures/tiny_diffusers.tar.xz") as archive:
        archive.extractall(destination, filter="data")
    return destination


@pytest.mark.parametrize("task", ["sd", "xl", "img2img", "inpaint"])
def test_saved_pipeline_preprocessing_trajectory_and_reload(saved_pipelines, task):
    # A process per pipeline releases JAX executable caches, including autodiff.
    command = [sys.executable, str(ROOT / "tools/check_diffusers_pipeline.py"), str(saved_pipelines / task)]
    if task in ("img2img", "inpaint"):
        command.append("--no-train")
    result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, timeout=180,
                            env={**os.environ, "JAX_PLATFORMS": "cpu", "USE_TF": "0",
                                 "PYTHONPATH": str(ROOT / "src"), "OMP_NUM_THREADS": "2",
                                 "OPENBLAS_NUM_THREADS": "1"})
    assert result.returncode == 0, result.stdout + result.stderr
