from tensorboard.compat.proto.event_pb2 import Event

class EventFileWriter:
    def __init__(self, logdir: str, max_queue_size: int = ..., flush_secs: int = ...,
                 filename_suffix: str = ...) -> None: ...
    def add_event(self, event: Event) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
