"""Check saved full-pipeline references using Dew's current runtime stack.

JAX_PLATFORMS=cpu USE_TF=0 PYTHONPATH=src python tools/check_diffusers_pipeline.py DIR
DIR is generated by diffusers_pipeline_reference.py in its isolated environment.
"""
import argparse
import json
import tempfile
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import optax
import transformers
from PIL import Image

from dew.interop.diffusers import load_pipeline
from dew.objectives.base import Step


def check(directory, train=True):
    reference = np.load(Path(directory) / "reference.npz")
    pipe = load_pipeline(directory, local_files_only=True)
    errors = {}

    def compare(name, actual, expected, atol=3e-5):
        actual, expected = np.asarray(actual), np.asarray(expected)
        errors[name] = float(np.max(np.abs(actual - expected)))
        np.testing.assert_allclose(actual, expected, atol=atol, rtol=atol)

    compare("tokens", pipe.encoder.tokenize(["cat"])["input_ids"], reference["tokens"], atol=0)
    given, null = pipe.conditions(["cat"], ["dog"])
    compare("hidden", given["conditioning"]["encoder_hidden_states"], reference["hidden"])
    if pipe.encoder.xl:
        compare("pooled", given["conditioning"]["added_cond_kwargs"]["text_embeds"], reference["pooled"])
        absent = pipe.conditions(["cat"])[1]["conditioning"]
        explicit = pipe.conditions(["cat"], "")[1]["conditioning"]
        np.testing.assert_array_equal(absent["encoder_hidden_states"], 0)
        assert np.any(explicit["encoder_hidden_states"] != absent["encoder_hidden_states"])
    key = jax.random.PRNGKey(17)
    noise = jnp.asarray(reference["noise"])
    pixels = jnp.asarray(reference["pixels"][None], jnp.float32) / 127.5 - 1
    compare("encode", pipe.autoencoder.encode(pipe.params["autoencoder"], pixels, key), reference["encoded"])
    compare("decode", pipe.autoencoder.decode(pipe.params["autoencoder"], noise), reference["decoded"])
    kwargs = {}
    if pipe.task != "text-to-image":
        kwargs["image"] = Image.fromarray(reference["pixels"])
        if pipe.task == "inpainting":
            kwargs["mask"] = Image.fromarray(reference["mask"])
        else:
            kwargs["strength"] = 1.0
        processed, masks = pipe.prepare_image(kwargs["image"], kwargs.get("mask"))
        compare("preprocess", processed.transpose(0, 3, 1, 2), reference["processed"], atol=0)
        if masks is not None:
            compare("mask", masks.transpose(0, 3, 1, 2), reference["processed_mask"], atol=0)
    else:
        compare("prediction", pipe.model.apply(pipe.params, noise, jnp.asarray([10]), **given), reference["prediction"])
        _, epsilon = pipe.process.denoiser(pipe.model, pipe.params, given)(noise, jnp.asarray([10]))
        compare("process_prediction", epsilon, reference["prediction"])
    images = pipe(["cat"], negative_prompts=["dog"], key=key, steps=2, guidance=3.0, latents=noise, **kwargs)
    compare("trajectory_images", (images + 1) / 2, reference["images"])
    training = None
    if train and pipe.task != "inpainting":
        objective = pipe.objective(unconditional_prob=0.0, ema_decay=None, steps=2)
        variables = objective.init(key)
        batch = {"image": reference["pixels"][None], **pipe.inputs.tokenize(["cat"])}
        step = Step(step=jnp.asarray(0), key=key, ema=None)
        def loss(params):
            value, _ = objective.loss({**variables, "params": params}, batch, step)
            return value.total / value.mass
        value, grads = jax.jit(jax.value_and_grad(loss))(variables["params"])
        norm = optax.global_norm(grads)
        assert np.isfinite(value) and float(norm) > 0
        updated = optax.apply_updates(variables["params"], jax.tree.map(lambda g: -1e-3 * g, grads))
        after = loss(updated)
        assert float(after) < float(value), (value, after)
        pipe = pipe.bind({**variables, "params": updated})
        training = {"loss_before": float(value), "loss_after": float(after), "gradient_norm": float(norm)}
        # Keep compiled autodiff from retaining the full training graph for reload proof.
        jax.clear_caches()
    with tempfile.TemporaryDirectory(prefix="dew-diffusers-reload-") as saved:
        pipe.save_pretrained(saved)
        loaded = load_pipeline(saved, local_files_only=True)
        before = pipe(["cat"], negative_prompts=["dog"], key=key, steps=2, guidance=3.0, latents=noise, **kwargs)
        after = loaded(["cat"], negative_prompts=["dog"], key=key, steps=2, guidance=3.0, latents=noise, **kwargs)
        compare("reload", after, before, atol=0)
    result = {"task": pipe.task, "xl": pipe.encoder.xl, "backend": jax.default_backend(),
              "transformers": transformers.__version__, "max_absolute_errors": errors, "training": training}
    print(json.dumps(result))
    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory")
    parser.add_argument("--no-train", action="store_true")
    args = parser.parse_args()
    check(args.directory, train=not args.no_train)
