/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=live/wrangler.jsonc --include-runtime=false live/worker-configuration.d.ts` (hash: 060024f6befc2b0bb16cf02eb2e28a10)
interface __BaseEnv_Env {
	REQUESTS: RateLimit;
	SNAPSHOT_COMMIT: "set-by-live-deploy";
	ALLOWED_ORIGINS: "https://preview.dewml.dev" | "https://dewml.dev";
	TURNSTILE_HOSTNAMES: "preview.dewml.dev" | "dewml.dev";
	TURNSTILE_TEST_KEYS: "accept" | "refuse";
	BUDGET_SECONDS: "14400" | "144000";
	MAX_SESSIONS: "2" | "8";
	WALL_SECONDS: "1200";
	WARM_SECONDS: "600";
	IDLE_SECONDS: "300";
	CPU_SECONDS: "900";
	IP_WINDOW_SECONDS: "600";
	IP_STARTS: "10" | "3";
	COORDINATOR: DurableObjectNamespace<import("./src/index").Coordinator>;
	SHARED: DurableObjectNamespace<import("./src/index").SharedHost> | DurableObjectNamespace<import("./src/index").SharedHost>;
	POOL: DurableObjectNamespace<import("./src/index").ModelPool> | DurableObjectNamespace<import("./src/index").ModelPool>;
	SNAPSHOTS: DurableObjectNamespace<import("./src/index").SnapshotRegistry> | DurableObjectNamespace<import("./src/index").SnapshotRegistry>;
	PREPARER: DurableObjectNamespace<import("./src/index").SnapshotPreparer> | DurableObjectNamespace<import("./src/index").SnapshotPreparer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Coordinator" | "SharedHost" | "SnapshotRegistry" | "SnapshotPreparer" | "ModelPool";
	}
	interface PreviewEnv {
		REQUESTS: RateLimit;
		SNAPSHOT_COMMIT: "set-by-live-deploy";
		ALLOWED_ORIGINS: "https://preview.dewml.dev";
		TURNSTILE_HOSTNAMES: "preview.dewml.dev";
		TURNSTILE_TEST_KEYS: "accept";
		BUDGET_SECONDS: "14400";
		MAX_SESSIONS: "2";
		WALL_SECONDS: "1200";
		WARM_SECONDS: "600";
		IDLE_SECONDS: "300";
		CPU_SECONDS: "900";
		IP_WINDOW_SECONDS: "600";
		IP_STARTS: "10";
		COORDINATOR: DurableObjectNamespace<import("./src/index").Coordinator>;
		SHARED: DurableObjectNamespace<import("./src/index").SharedHost>;
		POOL: DurableObjectNamespace<import("./src/index").ModelPool>;
		SNAPSHOTS: DurableObjectNamespace<import("./src/index").SnapshotRegistry>;
		PREPARER: DurableObjectNamespace<import("./src/index").SnapshotPreparer>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SNAPSHOT_COMMIT" | "ALLOWED_ORIGINS" | "TURNSTILE_HOSTNAMES" | "TURNSTILE_TEST_KEYS" | "BUDGET_SECONDS" | "MAX_SESSIONS" | "WALL_SECONDS" | "WARM_SECONDS" | "IDLE_SECONDS" | "CPU_SECONDS" | "IP_WINDOW_SECONDS" | "IP_STARTS">> {}
}
