/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=live/wrangler.jsonc --include-runtime=false live/worker-configuration.d.ts` (hash: 619b807ab3a34c570479e238a2ba6972)
interface __BaseEnv_Env {
	REQUESTS: RateLimit;
	ALLOWED_ORIGINS: "https://dewml.dev https://preview.dewml.dev";
	TURNSTILE_HOSTNAMES: "dewml.dev preview.dewml.dev";
	BUDGET_SECONDS: "144000";
	MAX_SESSIONS: "8";
	WALL_SECONDS: "1200";
	IDLE_SECONDS: "300";
	CPU_SECONDS: "900";
	IP_WINDOW_SECONDS: "600";
	IP_STARTS: "3";
	KERNEL: DurableObjectNamespace<import("./src/index").Kernel>;
	COORDINATOR: DurableObjectNamespace<import("./src/index").Coordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Kernel" | "Coordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "TURNSTILE_HOSTNAMES" | "BUDGET_SECONDS" | "MAX_SESSIONS" | "WALL_SECONDS" | "IDLE_SECONDS" | "CPU_SECONDS" | "IP_WINDOW_SECONDS" | "IP_STARTS">> {}
}
